export type Decision = "READY" | "REVIEW" | "BLOCKED" | "UNKNOWN";
export type EvidenceStatus = "complete" | "missing" | "denied" | "stale" | "timed_out" | "unavailable" | "invalid" | "skipped";
export type RunState = "accepted" | "queued" | "planning" | "resolving_asset" | "evidence_pending" | "evidence_partial" | "composing" | "validating" | "needs_input" | "succeeded" | "cancel_requested" | "canceled" | "expired" | "failed";
export interface TimeWindow { start: string; end: string }
export interface MediaContext { show_or_campaign?: string; asset_type?: string }
export interface RunRequest { schema_version: "run-request@1"; problem_statement: string; asset_hint?: string; container_hint?: string; purpose?: string; time_window?: TimeWindow; media_context?: MediaContext }
export interface ReadinessPlan { schema_version: "readiness-plan@1"; workflow: "audience_data_readiness"; asset_query?: string; container_query?: string; purpose?: string; time_window?: TimeWindow; required_evidence: ["asset", "quality", "governance", "lineage"]; clarification: null | { question: string } }
export interface EvidenceRecord { evidence_id: string; run_id: string; check_kind: "asset" | "quality" | "governance" | "lineage"; status: EvidenceStatus; facts: Record<string, string | number | boolean | null>; units: Record<string, string>; provider_id: string; provider_backend: string; semantic_operation: string; source_reference: string; authority_class: string; observed_at: string; fresh_until?: string; response_hash: string; policy_version: string; provenance: string }
export interface EvidenceBundle { schema_version: "evidence-bundle@1"; asset: { status: EvidenceStatus; asset_id?: string; display_name?: string; evidence_ids: string[] }; branches: { quality: { status: EvidenceStatus; evidence_ids: string[] }; governance: { status: EvidenceStatus; evidence_ids: string[] }; lineage: { status: EvidenceStatus; evidence_ids: string[] } }; coverage: Record<string, string[]> }
export interface PolicyDecision { schema_version: "policy-decision@1"; decision: Decision; policy_version: string; reasons: Array<{ code: string; evidence_ids: string[] }>; hard_stop: boolean }
export interface BriefDraft { schema_version: "brief-draft@1"; headline: string; summary: string; summary_evidence_ids: string[]; risks: Array<{ severity: "low" | "medium" | "high"; kind: string; text: string; evidence_ids: string[] }>; recommendations: string[]; cited_evidence_ids: string[] }
export interface Provenance { model: string; provider: string; label: string; model_backend: Record<string, unknown>; provider_backend: Record<string, unknown>; metrics: Record<string, unknown> }
export interface ReadinessBrief { schema_version: "readiness-brief@1"; run_id: string; workflow: string; run_status: RunState; decision: Decision; headline: string; summary: string; resolved_asset: { asset_id: string; display_name: string; workspace: string; evidence_id: string } | null; summary_evidence_ids: string[]; checks: unknown[]; risks: unknown[]; recommendations: string[]; gaps: unknown[]; coverage: unknown; policy_version: string; policy_disclosure: string; policy_reasons?: unknown[]; policy_decision?: PolicyDecision; provenance: Provenance; final_policy_recomputed?: boolean; policy_comparison?: Record<string, unknown>; evidence_bundle?: EvidenceBundle; limitations: string[] }
export interface RunEvent { schema_version: "run-event@1"; run_id: string; seq: number; type: string; step: string; state: RunState; display: string; payload: Record<string, unknown>; occurred_at: string }
export interface GroundingDocument { schema_version: "grounding-document@1"; document_id: string; filename: string; media_type: "application/pdf" | "text/plain"; byte_size: number; text_char_count: number; truncated: boolean; source_label: string; chunk_count: number; ingestion: Record<string, unknown> }
export interface GroundedBriefProposal { schema_version: "grounded-script-brief@1"; title: string; summary: string; key_points: Array<{ text: string; citation_ids: string[] }>; cited_citation_ids: string[] }
export interface ScriptBriefClaim { text: string; citation_ids: string[] }
export type ProducerSignalCategory = "props" | "vehicles" | "costume" | "set" | "stunts" | "vfx" | "sound" | "weather" | "crowds" | "minors" | "animals" | "company_moves" | "continuity" | "scheduling";
export interface ProducerIntelligence { schema_version: "producer-intelligence@1"; scene_breakdown: Array<{ scene_heading: string; location_wording: string; int_ext: "INT" | "EXT" | "INT/EXT" | "not stated in the source"; time_of_day: "DAY" | "NIGHT" | "not stated in the source"; citation_ids: string[] }>; cast_and_role_demands: Array<{ role: string; demand: string; citation_ids: string[] }>; production_signals: Array<{ category: ProducerSignalCategory; value: string; citation_ids: string[] }>; production_risks: Array<{ risk: string; citation_ids: string[] }>; gaps_and_questions: Array<{ category: string; question: string; citation_ids: string[] }> }
export interface ScriptBriefProposal { schema_version: "grounded-script-brief@2"; title: string; logline: ScriptBriefClaim; synopsis: ScriptBriefClaim; main_characters: Array<{ name: string; description: string; citation_ids: string[] }>; setting_tone_themes: { setting: string; tone: string; themes: string[]; citation_ids: string[] }; production_details: Array<{ label: string; value: string; citation_ids: string[] }>; producer_intelligence?: ProducerIntelligence; open_questions: Array<{ question: string; citation_ids: string[] }>; cited_citation_ids: string[] }
export interface GroundedBriefRequest { schema_version: "grounded-brief-request@1"; question: string }
export interface ScriptBriefRequest { schema_version: "grounded-brief-request@2"; request?: string; question?: string }
export interface GroundedBriefResult { schema_version: "grounded-script-result@1"; workflow: "grounded_script_brief"; status: "succeeded" | "grounding_gap"; brief_run_id: string; document_id: string; title: string; summary: string; key_points: Array<{ text: string; citation_ids: string[] }>; cited_citation_ids: string[]; citations: Array<{ citation_id: string; document_id: string; chunk_id: string; source_locations: unknown[]; source_label: string }>; grounding: Record<string, unknown>; provenance: Record<string, unknown>; limitations: string[] }
export interface ScriptBriefResult { schema_version: "grounded-script-result@2"; workflow: "script_brief"; status: "succeeded" | "grounding_gap"; brief_run_id: string; document_id: string; title: string; logline: ScriptBriefClaim; synopsis: ScriptBriefClaim; main_characters: Array<{ name: string; description: string; citation_ids: string[] }>; setting_tone_themes: { setting: string; tone: string; themes: string[]; citation_ids: string[] }; production_details: Array<{ label: string; value: string; citation_ids: string[] }>; producer_intelligence?: ProducerIntelligence; open_questions: Array<{ question: string; citation_ids: string[] }>; cited_citation_ids: string[]; citations: Array<{ citation_id: string; document_id: string; chunk_id: string; source_locations: unknown[]; source_label: string }>; grounding: Record<string, unknown>; provenance: Record<string, unknown>; limitations: string[] }
export type ProducerSourceKind = "primary_screenplay" | "screenplay_revision" | "director_notes" | "cast_notes" | "location_access" | "schedule_assumptions" | "budget_assumptions" | "rights_clearance" | "department_input" | "breakdown" | "handoff" | "script" | "cast_actor_notes" | "location_production_notes" | "schedule" | "budget" | "department_notes" | "other";
export type ProducerClassification = "source_fact" | "source_implied_inference" | "externally_supplied_fact" | "externally_researched_fact" | "human_assumption" | "conflict" | "open_question" | "decision";
export type ProducerEvidenceState = "established" | "supplied_not_verified" | "externally_researched_not_verified" | "assumed" | "not_established" | "conflict" | "recorded_decision" | "stale" | "unavailable";
export interface ProducerVersionProvenance { schema_version: "producer-version-provenance@1"; source_schema_version: "producer-source@1"; source_version: string | null; source_version_status: "stated_in_uploaded_source" | "not_stated_in_uploaded_source"; source_version_citation_ids?: string[]; identity_basis?: string }
export interface ProducerSourceInventory { schema_version: "producer-source@1"; source_id: string; document_id?: string; input_ref?: string | null; filename: string; media_type: "application/pdf" | "text/plain"; source_kind: ProducerSourceKind; source_label: string; department?: string | null; byte_size: number; content_hash: string; text_char_count?: number; truncated?: boolean; chunk_count?: number; locations?: unknown[]; version_label?: string | null; status_label?: string | null; relationships?: unknown[]; version_provenance?: ProducerVersionProvenance; ingestion?: Record<string, unknown>; ingestion_state?: string; limitations?: string[] }
export interface ProducerCitation { schema_version: "producer-citation@1"; citation_id: string; source_id: string; document_id: string; filename: string; media_type: "application/pdf" | "text/plain" | "text/html"; source_kind: ProducerSourceKind | "external_research"; source_label: string; source_locations: unknown[]; excerpt: string }
export interface ProducerStatement { text: string; citation_ids: string[]; claim_type: "fact" | "inference" | "unknown"; classification?: ProducerClassification; evidence_state?: ProducerEvidenceState; kind?: string; topic?: string; category?: string; source_id?: string; source_kind?: ProducerSourceKind; source_ids?: string[]; owner?: string | null; priority?: "high" | "medium" | "low" | "unset"; next_action?: string }
export interface ProducerCanonicalItem extends ProducerStatement { value?: string | null; field?: string; amount?: string | number | null; currency?: string | null; unit?: string | null; assertions?: ProducerCanonicalItem[]; question?: string; title?: string; related_to?: string | null; element_id?: string; department?: string | null; inference_basis?: string; priority_basis?: string; limitations?: string[] }
export interface ProducerRegisterEntry { schema_version: "producer-register-entry@1"; register_id: string; type: "decision" | "question"; title: string; action: string; owner_role: string; priority: "high" | "medium" | "low"; status: "open"; claim_type: "fact" | "inference" | "unknown"; citation_ids: string[]; source_ids: string[] }
// `producer-intake-decision-packet@1` is the PRD-target strict bounded contract (one primary_screenplay,
// source/version manifest, exact facts, conflicts, evidence states, and the full provenance object)
// produced by the `/v1/producer-source-bundles` path. `producer-decision-packet@1` remains a stable,
// unrenamed compatibility alias emitted only by the older free-label `/v1/producer-packets` multipart
// path; both shapes share this interface because the compatibility path only ever populates the
// optional PRD-shaped fields when its own source kinds happen to overlap with the strict allowlist.
export type ProducerPacketSchemaVersion = "producer-intake-decision-packet@1" | "producer-decision-packet@1";
export interface ProducerPacketProvenance { schema_version: "producer-provenance@1"; contract_version?: ProducerPacketSchemaVersion; mode: "demo"; backend: string; provider: string; external: false; read_only: true; grounding_strategy?: string; bundle_manifest_hash?: string; source_manifest_hash?: string; fallback_used?: boolean; retention_state?: string; external_evidence_enabled?: boolean; external_evidence_provider?: string | null }
export interface ProducerDecisionPacket { schema_version: ProducerPacketSchemaVersion; workflow: "producer_consolidation"; status: "succeeded"; packet_id: string; bundle_id?: string | null; created_at: string; bundle: { schema_version: "producer-source-bundle@1"; bundle_id?: string; source_count: number; source_ids: string[]; total_bytes: number; total_extracted_chars: number; manifest_hash?: string }; executive_summary: ProducerStatement; source_manifest?: ProducerSourceInventory[]; source_inventory: ProducerSourceInventory[]; exact_facts?: ProducerCanonicalItem[]; scene_index?: ProducerCanonicalItem[]; production_elements?: ProducerCanonicalItem[]; schedule_inputs?: ProducerCanonicalItem[]; budget_inputs?: ProducerCanonicalItem[]; rights_access_logistics?: ProducerCanonicalItem[]; conflicts?: ProducerCanonicalItem[]; decision_question_register?: ProducerCanonicalItem[]; gaps_and_next_steps?: ProducerCanonicalItem[]; external_evidence?: ProducerCanonicalItem[]; version_provenance: Record<string, unknown>; reconciliation: Record<string, unknown>; production_decisions: ProducerStatement[]; decision_register: ProducerRegisterEntry[]; locations_and_timing: ProducerStatement[]; cast_role_demands: ProducerStatement[]; department_requirements: ProducerStatement[]; risks_or_conflicts: ProducerStatement[]; cross_document_conflicts: ProducerStatement[]; gaps_or_questions: ProducerStatement[]; handoff: Record<string, unknown>; cited_citation_ids: string[]; citations: ProducerCitation[]; provenance: ProducerPacketProvenance; limitations: string[] }

export type PartnerEnvironment = "local" | "staging" | "production" | "unknown";
export type PartnerAuthMode = "none" | "none_synthetic" | "oauth2_client_credentials" | "oauth2_delegated" | "api_key_reference" | "adc" | "injected_reference" | "mtls_reference";
export type PartnerHealthState = "unknown" | "healthy" | "degraded" | "unavailable" | "denied" | "misconfigured" | "stale" | "circuit_open";
export type PartnerReadinessState = "unknown" | "ready" | "not_configured" | "missing_auth" | "stale" | "degraded" | "unavailable" | "denied" | "disabled" | "circuit_open";
export type PartnerOperation = "resolve_asset" | "describe_asset" | "read_metadata" | "read_quality" | "read_governance" | "read_lineage" | "search_metadata" | "search_governance" | "search_lineage" | "read_telemetry";
export type PartnerDataClass = "synthetic_asset" | "metadata" | "quality" | "governance" | "lineage" | "search" | "telemetry";
export interface PartnerOperationCapability { operation: PartnerOperation; tool_ref: string; read_only: true; data_class: PartnerDataClass; input_schema_hash?: string; output_schema_hash?: string }
export interface PartnerCapability { schema_version: "partner-capability@1"; provider: { provider_id: string; display_name: string; product_ref?: string; confirmation_state: "confirmed" | "pending" }; environment: PartnerEnvironment; endpoint_ref: string; auth_mode: PartnerAuthMode; credential_ref?: string; scope_ref?: string; allowed_operations: PartnerOperationCapability[]; data_classes: PartnerDataClass[]; health: { state: PartnerHealthState; checked_at?: string; detail?: string }; redacted_provenance: PartnerProvenance; manifest_hash: string; enabled: boolean; limits: { timeout_ms: number; max_attempts: number; max_response_bytes: number; max_items: number } }
export interface PartnerProvenance { schema_version: "partner-provenance@1"; provider_id: string | null; backend: string; environment: PartnerEnvironment; endpoint_ref: string | null; auth_mode: PartnerAuthMode | null; manifest_hash: string | null; operation?: string; observed_at?: string; response_hash?: string; redacted: true }
export interface PartnerReadiness { schema_version: "partner-readiness@1"; provider_id: string | null; provider_display_name: string | null; environment: string; endpoint_ref: string | null; auth_mode: string | null; scope_ref?: string | null; state: PartnerReadinessState; health: PartnerHealthState; checked_at: string | null; reason_codes: string[]; error_class?: string; circuit?: Record<string, unknown>; provenance: PartnerProvenance }
export interface PartnerEvent { schema_version: "partner-event@1"; event_id: string; provider_id: string | null; event_type: string; operation: PartnerOperation | null; attempt: number; state: string; delivery_id_hash?: string; error_class?: string; payload: Record<string, unknown>; occurred_at: string; redacted: true }
export interface PartnerProjection { schema_version: "partner-projection@1"; provider: PartnerCapability["provider"] | null; environment: PartnerEnvironment; endpoint_ref: string | null; auth_mode: string | null; scope_ref?: string | null; allowed_operations: PartnerOperation[]; data_classes: PartnerDataClass[]; enabled: boolean; health: PartnerCapability["health"]; readiness: PartnerReadiness; provenance: PartnerProvenance }
