export type Decision = "READY" | "REVIEW" | "BLOCKED" | "UNKNOWN";
export type EvidenceStatus = "complete" | "missing" | "denied" | "stale" | "timed_out" | "unavailable" | "invalid" | "skipped";
export type RunState = "accepted" | "queued" | "planning" | "resolving_asset" | "evidence_pending" | "evidence_partial" | "composing" | "validating" | "needs_input" | "succeeded" | "cancel_requested" | "canceled" | "expired" | "failed";
export interface TimeWindow { start: string; end: string }
export interface MediaContext { show_or_campaign?: string; asset_type?: string }
export interface RunRequest { schema_version: "run-request@1"; problem_statement: string; asset_hint?: string; container_hint?: string; purpose?: string; time_window?: TimeWindow; media_context?: MediaContext }
export interface ReadinessPlan { schema_version: "readiness-plan@1"; workflow: "audience_data_readiness"; asset_query?: string; container_query?: string; purpose?: string; time_window?: TimeWindow; required_evidence: ["asset", "quality", "governance", "lineage"]; clarification: null | { question: string } }
export interface EvidenceRecord { evidence_id: string; run_id: string; check_kind: "asset" | "quality" | "governance" | "lineage"; status: EvidenceStatus; facts: Record<string, string | number | boolean | null>; units: Record<string, string>; provider_id: string; provider_backend: string; semantic_operation: string; source_reference: string; authority_class: string; observed_at: string; fresh_until?: string; response_hash: string; policy_version: string; provenance: string }
export interface PolicyDecision { schema_version: "policy-decision@1"; decision: Decision; policy_version: string; reasons: Array<{ code: string; evidence_ids: string[] }>; hard_stop: boolean }
export interface BriefDraft { schema_version: "brief-draft@1"; headline: string; summary: string; summary_evidence_ids: string[]; risks: Array<{ severity: "low" | "medium" | "high"; kind: string; text: string; evidence_ids: string[] }>; recommendations: string[]; cited_evidence_ids: string[] }
export interface ReadinessBrief { schema_version: "readiness-brief@1"; run_id: string; workflow: string; run_status: RunState; decision: Decision; headline: string; summary: string; resolved_asset: { asset_id: string; display_name: string; workspace: string; evidence_id: string } | null; summary_evidence_ids: string[]; checks: unknown[]; risks: unknown[]; recommendations: string[]; gaps: unknown[]; coverage: unknown; policy_version: string; policy_disclosure: string; provenance: { model: string; provider: string; label: string }; limitations: string[] }
export interface RunEvent { schema_version: "run-event@1"; run_id: string; seq: number; type: string; step: string; state: RunState; display: string; payload: Record<string, unknown>; occurred_at: string }
