export type Decision = "READY" | "REVIEW" | "BLOCKED" | "UNKNOWN";
export type EvidenceStatus = "complete" | "missing" | "denied" | "stale" | "timed_out" | "unavailable" | "invalid" | "skipped";
export type RunState = "accepted" | "queued" | "planning" | "resolving_asset" | "evidence_pending" | "evidence_partial" | "composing" | "validating" | "needs_input" | "succeeded" | "cancel_requested" | "canceled" | "expired" | "failed";
export interface TimeWindow { start: string; end: string }
export interface MediaContext { show_or_campaign?: string; asset_type?: string }
export interface RunRequest { schema_version: "run-request@1"; problem_statement: string; asset_hint?: string; container_hint?: string; purpose?: string; time_window?: TimeWindow; media_context?: MediaContext }
export interface ReadinessPlan { schema_version: "readiness-plan@1"; workflow: "audience_data_readiness"; asset_query?: string; container_query?: string; purpose?: string; time_window?: TimeWindow; required_evidence: ["asset", "quality", "governance", "lineage"]; clarification: null | { question: string } }
export interface EvidenceRecord { evidence_id: string; run_id: string; check_kind: "asset" | "quality" | "governance" | "lineage"; status: EvidenceStatus; facts: Record<string, string | number | boolean | null>; units: Record<string, string>; provider_id: string; provider_backend: string; semantic_operation: string; source_reference: string; authority_class: string; observed_at: string; fresh_until?: string; response_hash: string; policy_version: string; provenance: string }
export interface EvidenceBundle { schema_version: "evidence-bundle@1"; asset: { status: EvidenceStatus; asset_id?: string; display_name?: string; evidence_ids: string[] }; branches: { quality: { status: EvidenceStatus; evidence_ids: string[] }; governance: { status: EvidenceStatus; evidence_ids: string[] }; lineage: { status: EvidenceStatus; evidence_ids: string[] } }; coverage: Record<string, string[]> }
export interface PolicyDecision { schema_version: "policy-decision@1"; decision: Decision; policy_version: string; reasons: Array<{ code: string; evidence_ids: string[] }>; hard_stop: boolean }
export interface BriefDraft { schema_version: "brief-draft@1"; headline: string; summary: string; summary_evidence_ids: string[]; risks: Array<{ severity: "low" | "medium" | "high"; kind: string; text: string; evidence_ids: string[] }>; recommendations: string[]; cited_evidence_ids: string[] }
export interface Provenance { model: string; provider: string; label: string; model_backend: Record<string, unknown>; provider_backend: Record<string, unknown>; metrics: Record<string, unknown> }
export interface ReadinessBrief { schema_version: "readiness-brief@1"; run_id: string; workflow: string; run_status: RunState; decision: Decision; headline: string; summary: string; resolved_asset: { asset_id: string; display_name: string; workspace: string; evidence_id: string } | null; summary_evidence_ids: string[]; checks: unknown[]; risks: unknown[]; recommendations: string[]; gaps: unknown[]; coverage: unknown; policy_version: string; policy_disclosure: string; policy_reasons?: unknown[]; policy_decision?: PolicyDecision; provenance: Provenance; final_policy_recomputed?: boolean; policy_comparison?: Record<string, unknown>; evidence_bundle?: EvidenceBundle; limitations: string[] }
export interface RunEvent { schema_version: "run-event@1"; run_id: string; seq: number; type: string; step: string; state: RunState; display: string; payload: Record<string, unknown>; occurred_at: string }
export interface GroundingDocument { schema_version: "grounding-document@1"; document_id: string; filename: string; media_type: "application/pdf" | "text/plain"; byte_size: number; text_char_count: number; truncated: boolean; source_label: string; chunk_count: number; ingestion: Record<string, unknown> }
export interface GroundedBriefProposal { schema_version: "grounded-script-brief@1"; title: string; summary: string; key_points: Array<{ text: string; citation_ids: string[] }>; cited_citation_ids: string[] }
export interface ScriptBriefClaim { text: string; citation_ids: string[] }
export type ProducerSignalCategory = "props" | "vehicles" | "costume" | "set" | "stunts" | "vfx" | "sound" | "weather" | "crowds" | "minors" | "animals" | "company_moves" | "continuity" | "scheduling";
export interface ProducerIntelligence { schema_version: "producer-intelligence@1"; scene_breakdown: Array<{ scene_heading: string; location_wording: string; int_ext: "INT" | "EXT" | "INT/EXT" | "not stated in the source"; time_of_day: "DAY" | "NIGHT" | "not stated in the source"; citation_ids: string[] }>; cast_and_role_demands: Array<{ role: string; demand: string; citation_ids: string[] }>; production_signals: Array<{ category: ProducerSignalCategory; value: string; citation_ids: string[] }>; production_risks: Array<{ risk: string; citation_ids: string[] }>; gaps_and_questions: Array<{ category: string; question: string; citation_ids: string[] }> }
export interface ScriptBriefProposal { schema_version: "grounded-script-brief@2"; title: string; logline: ScriptBriefClaim; synopsis: ScriptBriefClaim; main_characters: Array<{ name: string; description: string; citation_ids: string[] }>; setting_tone_themes: { setting: string; tone: string; themes: string[]; citation_ids: string[] }; production_details: Array<{ label: string; value: string; citation_ids: string[] }>; producer_intelligence?: ProducerIntelligence; open_questions: Array<{ question: string; citation_ids: string[] }>; cited_citation_ids: string[] }
export interface GroundedBriefRequest { schema_version: "grounded-brief-request@1"; question: string }
export interface ScriptBriefRequest { schema_version: "grounded-brief-request@2"; request?: string; question?: string }
export interface GroundedBriefResult { schema_version: "grounded-script-result@1"; workflow: "grounded_script_brief"; status: "succeeded" | "grounding_gap"; brief_run_id: string; document_id: string; title: string; summary: string; key_points: Array<{ text: string; citation_ids: string[] }>; cited_citation_ids: string[]; citations: Array<{ citation_id: string; document_id: string; chunk_id: string; source_locations: unknown[]; source_label: string }>; grounding: Record<string, unknown>; provenance: Record<string, unknown>; limitations: string[] }
export interface ScriptBriefResult { schema_version: "grounded-script-result@2"; workflow: "script_brief"; status: "succeeded" | "grounding_gap"; brief_run_id: string; document_id: string; title: string; logline: ScriptBriefClaim; synopsis: ScriptBriefClaim; main_characters: Array<{ name: string; description: string; citation_ids: string[] }>; setting_tone_themes: { setting: string; tone: string; themes: string[]; citation_ids: string[] }; production_details: Array<{ label: string; value: string; citation_ids: string[] }>; producer_intelligence?: ProducerIntelligence; open_questions: Array<{ question: string; citation_ids: string[] }>; cited_citation_ids: string[]; citations: Array<{ citation_id: string; document_id: string; chunk_id: string; source_locations: unknown[]; source_label: string }>; grounding: Record<string, unknown>; provenance: Record<string, unknown>; limitations: string[] }

export type PartnerEnvironment = "local" | "staging" | "production" | "unknown";
export type PartnerAuthMode = "none" | "none_synthetic" | "oauth2_client_credentials" | "oauth2_delegated" | "api_key_reference" | "adc" | "injected_reference" | "mtls_reference";
export type PartnerHealthState = "unknown" | "healthy" | "degraded" | "unavailable" | "denied" | "misconfigured" | "stale" | "circuit_open";
export type PartnerReadinessState = "unknown" | "ready" | "not_configured" | "missing_auth" | "stale" | "degraded" | "unavailable" | "denied" | "disabled" | "circuit_open";
export type PartnerOperation = "resolve_asset" | "describe_asset" | "read_metadata" | "read_quality" | "read_governance" | "read_lineage" | "search_metadata" | "search_governance" | "search_lineage" | "read_telemetry";
export type PartnerDataClass = "synthetic_asset" | "metadata" | "quality" | "governance" | "lineage" | "search" | "telemetry";
export interface PartnerOperationCapability { operation: PartnerOperation; tool_ref: string; read_only: true; data_class: PartnerDataClass; input_schema_hash?: string; output_schema_hash?: string }
export interface PartnerCapability { schema_version: "partner-capability@1"; provider: { provider_id: string; display_name: string; product_ref?: string; confirmation_state: "confirmed" | "pending" }; environment: PartnerEnvironment; endpoint_ref: string; auth_mode: PartnerAuthMode; credential_ref?: string; scope_ref?: string; allowed_operations: PartnerOperationCapability[]; data_classes: PartnerDataClass[]; health: { state: PartnerHealthState; checked_at?: string; detail?: string }; redacted_provenance: PartnerProvenance; manifest_hash: string; enabled: boolean; limits: { timeout_ms: number; max_attempts: number; max_response_bytes: number; max_items: number } }
export interface PartnerProvenance { schema_version: "partner-provenance@1"; provider_id: string | null; backend: string; environment: PartnerEnvironment; endpoint_ref: string | null; auth_mode: PartnerAuthMode | null; manifest_hash: string | null; operation?: string; observed_at?: string; response_hash?: string; redacted: true }
export interface PartnerReadiness { schema_version: "partner-readiness@1"; provider_id: string | null; provider_display_name: string | null; environment: string; endpoint_ref: string | null; auth_mode: string | null; scope_ref?: string | null; state: PartnerReadinessState; health: PartnerHealthState; checked_at: string | null; reason_codes: string[]; error_class?: string; circuit?: Record<string, unknown>; provenance: PartnerProvenance }
export interface PartnerEvent { schema_version: "partner-event@1"; event_id: string; provider_id: string | null; event_type: string; operation: PartnerOperation | null; attempt: number; state: string; delivery_id_hash?: string; error_class?: string; payload: Record<string, unknown>; occurred_at: string; redacted: true }
export interface PartnerProjection { schema_version: "partner-projection@1"; provider: PartnerCapability["provider"] | null; environment: PartnerEnvironment; endpoint_ref: string | null; auth_mode: string | null; scope_ref?: string | null; allowed_operations: PartnerOperation[]; data_classes: PartnerDataClass[]; enabled: boolean; health: PartnerCapability["health"]; readiness: PartnerReadiness; provenance: PartnerProvenance }
